FROM node:lts-bookworm-slim AS builder
WORKDIR /app
COPY package.json yarn.lock ./
RUN yarn install --frozen-lockfile
COPY . .
RUN yarn run build:reader

FROM node:lts-bookworm-slim AS production
RUN addgroup app && adduser -S -G app app
USER app
ARG NODE_ENV=production
ENV NODE_ENV=${NODE_ENV}
WORKDIR /app
COPY --from=builder /app/dist/apps/reader/apps/reader ./dist/reader
COPY --from=builder /app/dist/apps/reader/libs/ ./libs
COPY --from=builder /app/node_modules ./node_modules
CMD ["node", "dist/reader/src/main.js"]

