#!/bin/bash

set -e

echo "[postgres-script] Init PostgreSQL database..."

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE USER $POSTGRES_USER;
    CREATE DATABASE $POSTGRES_DB;
    GRANT ALL PRIVILEGES ON DATABASE $POSTGRES_DB TO $POSTGRES_USER;
    ALTER USER $POSTGRES_USER WITH ENCRYPTED PASSWORD "$POSTGRES_PASSWORD";
EOSQL
